//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganBankStockTable
    {
        public int OrganBankStockID { get; set; }
        public int OrganTypeID { get; set; }
        public bool Stauts { get; set; }
        public int Quantity { get; set; }
        public string Description { get; set; }
        public int OrganBankID { get; set; }
    
        public virtual OrganBankTable OrganBankTable { get; set; }
        public virtual OrganTypeTable OrganTypeTable { get; set; }
    }
}
