//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganDonorTable
    {
        public int OrganDonorID { get; set; }
        public string OrganDonorName { get; set; }
        public int OrganTypeID { get; set; }
        public string LastDonatedOrgan { get; set; }
        public string NID { get; set; }
        public string Location { get; set; }
        public int CityID { get; set; }
        public string HealthIssues { get; set; }
        public int UserID { get; set; }
        public int GenderID { get; set; }
        public string ContactNo { get; set; }
    
        public virtual CityTable CityTable { get; set; }
        public virtual OrganTypeTable OrganTypeTable { get; set; }
        public virtual UserTable UserTable { get; set; }
        public virtual GenderTable GenderTable { get; set; }
    }
}
